[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
dimensions = { columns = 95, lines = 24 }
dynamic_padding = true

[scrolling]
history = 100000

[font]
normal = { family = "Moralerspace Neon JPDOC", style = "Regular" }
size = 13

[mouse]
hide_when_typing = true

